--------------------------------------------------------------------------------
-- (c) Copyright 2010 - 2013 Xilinx, Inc. All rights reserved.
--
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
--
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
--------------------------------------------------------------------------------
-- Description:
-- This is an example testbench for the DDS Compiler IP core.
-- The testbench has been generated by Vivado to accompany the IP core
-- instance you have generated.
--
-- This testbench is for demonstration purposes only.  See note below for
-- instructions on how to use it with your core.
--
-- See the DDS Compiler product guide for further information
-- about this core.
--
--------------------------------------------------------------------------------
-- Using this testbench
--
-- This testbench instantiates your generated DDS Compiler core
-- instance named "dds_compiler_test".
--
-- Use Vivado's Run Simulation flow to run this testbench.  See the Vivado
-- documentation for details.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;

entity tb_dds_compiler_test is
end tb_dds_compiler_test;

architecture tb of tb_dds_compiler_test is

  -----------------------------------------------------------------------
  -- Timing constants
  -----------------------------------------------------------------------
  constant CLOCK_PERIOD : time := 100 ns;
  constant T_HOLD       : time := 10 ns;
  constant T_STROBE     : time := CLOCK_PERIOD - (1 ns);

  -----------------------------------------------------------------------
  -- DUT input signals
  -----------------------------------------------------------------------

  -- General inputs
  signal aclk                            : std_logic := '0';  -- the master clock

  -- Config slave channel signals
  signal s_axis_config_tvalid            : std_logic := '0';  -- payload is valid
  signal s_axis_config_tdata             : std_logic_vector(63 downto 0) := (others => '0');  -- data payload
  signal s_axis_config_tlast             : std_logic := '0';  -- indicates end of packet

  -- Data master channel signals
  signal m_axis_data_tvalid              : std_logic := '0';  -- payload is valid
  signal m_axis_data_tdata               : std_logic_vector(7 downto 0) := (others => '0');  -- data payload

  -- Phase master channel signals
  signal m_axis_phase_tvalid             : std_logic := '0';  -- payload is valid
  signal m_axis_phase_tdata              : std_logic_vector(31 downto 0) := (others => '0');  -- data payload

  -- Event signals
  signal event_s_config_tlast_missing    : std_logic := '0';
  signal event_s_config_tlast_unexpected : std_logic := '0';

  -----------------------------------------------------------------------
  -- Aliases for AXI channel TDATA and TUSER fields
  -- These are a convenience for viewing data in a simulator waveform viewer.
  -- If using ModelSim or Questa, add "-voptargs=+acc=n" to the vsim command
  -- to prevent the simulator optimizing away these signals.
  -----------------------------------------------------------------------

  -- Config slave channel alias signals
  signal s_axis_config_tdata_inc       : std_logic_vector(24 downto 0) := (others => '0');
  signal s_axis_config_tdata_off       : std_logic_vector(24 downto 0) := (others => '0');

  -- Data master channel alias signals
  signal m_axis_data_tdata_sine        : std_logic_vector(7 downto 0) := (others => '0');
  -- Alias signals for each separate TDM channel (these are 1 cycle delayed relative to the above alias signals)
  signal m_axis_data_channel           : integer := 0;  -- indicates TDM channel number of data master channel outputs
  signal m_axis_data_tdata_sine_c0     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c1     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c2     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c3     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c4     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c5     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c6     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c7     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c8     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c9     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c10     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c11     : std_logic_vector(7 downto 0) := (others => '0');
  signal m_axis_data_tdata_sine_c12     : std_logic_vector(7 downto 0) := (others => '0');

  -- Phase master channel alias signals
  signal m_axis_phase_tdata_phase      : std_logic_vector(24 downto 0) := (others => '0');
  -- Alias signals for each separate TDM channel (these are 1 cycle delayed relative to the above alias signals)
  signal m_axis_phase_channel          : integer := 0;  -- indicates TDM channel number of phase master channel outputs
  signal m_axis_phase_tdata_phase_c0   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c1   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c2   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c3   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c4   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c5   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c6   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c7   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c8   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c9   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c10   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c11   : std_logic_vector(24 downto 0) := (others => '0');
  signal m_axis_phase_tdata_phase_c12   : std_logic_vector(24 downto 0) := (others => '0');


  signal end_of_simulation : boolean := false;
     
begin

  -----------------------------------------------------------------------
  -- Instantiate the DUT
  -----------------------------------------------------------------------

  dut : entity work.dds_compiler_test
    port map (
      aclk                            => aclk
      ,s_axis_config_tvalid            => s_axis_config_tvalid
      ,s_axis_config_tdata             => s_axis_config_tdata
      ,s_axis_config_tlast             => s_axis_config_tlast
      ,m_axis_data_tvalid              => m_axis_data_tvalid
      ,m_axis_data_tdata               => m_axis_data_tdata
      ,m_axis_phase_tvalid             => m_axis_phase_tvalid
      ,m_axis_phase_tdata              => m_axis_phase_tdata
      ,event_s_config_tlast_missing    => event_s_config_tlast_missing
      ,event_s_config_tlast_unexpected => event_s_config_tlast_unexpected
      );

  -----------------------------------------------------------------------
  -- Generate clock
  -----------------------------------------------------------------------

  clock_gen : process
  begin
    aclk <= '0';
    if (end_of_simulation) then
      wait;
    else
      wait for CLOCK_PERIOD;
      loop
        aclk <= '0';
        wait for CLOCK_PERIOD/2;
        aclk <= '1';
        wait for CLOCK_PERIOD/2;
      end loop;
    end if;
  end process clock_gen;

  -----------------------------------------------------------------------
  -- Generate inputs
  -----------------------------------------------------------------------

  stimuli : process
  begin

    -- Drive inputs T_HOLD time after rising edge of clock
    wait until rising_edge(aclk);
    wait for T_HOLD;

    -- Program the core with the initial configuration.
    -- The phase increment and phase offset values here are derived from the output frequency and
    -- phase offset angle values set in the CORE Generator GUI.
    -- The config slave channel packet is one transaction per TDM channel
    for cfg_channel in 0 to 12 loop
      s_axis_config_tvalid <= '1';
      s_axis_config_tdata <= (others => '0');  -- set unused TDATA bits to zero
      case cfg_channel is
        when 0 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 0 phase increment
          s_axis_config_tdata(56 downto 32) <= "1000110100011011011100011";  -- channel 0 phase offset
        when 1 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 1 phase increment
          s_axis_config_tdata(56 downto 32) <= "1010000000000000000000000";  -- channel 1 phase offset
        when 2 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 2 phase increment
          s_axis_config_tdata(56 downto 32) <= "1011001011100100100011110";  -- channel 2 phase offset
        when 3 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 3 phase increment
          s_axis_config_tdata(56 downto 32) <= "0100110100011011011100011";  -- channel 3 phase offset
        when 4 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 4 phase increment
          s_axis_config_tdata(56 downto 32) <= "0010000000000000000000000";  -- channel 4 phase offset
        when 5 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 5 phase increment
          s_axis_config_tdata(56 downto 32) <= "0001001011100100100011110";  -- channel 5 phase offset
        when 6 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 6 phase increment
          s_axis_config_tdata(56 downto 32) <= "0000110100011011011100010";  -- channel 6 phase offset
        when 7 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 7 phase increment
          s_axis_config_tdata(56 downto 32) <= "0010000000000000000000000";  -- channel 7 phase offset
        when 8 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 8 phase increment
          s_axis_config_tdata(56 downto 32) <= "0011001011100100100011101";  -- channel 8 phase offset
        when 9 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 9 phase increment
          s_axis_config_tdata(56 downto 32) <= "0100110100011011011100010";  -- channel 9 phase offset
        when 10 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 10 phase increment
          s_axis_config_tdata(56 downto 32) <= "0110000000000000000000000";  -- channel 10 phase offset
        when 11 =>
          s_axis_config_tdata(24 downto 0) <= "0000000011010100111111011";  -- channel 11 phase increment
          s_axis_config_tdata(56 downto 32) <= "0111001011100100100011101";  -- channel 11 phase offset
        when 12 =>
          s_axis_config_tdata(24 downto 0) <= "0000000000000000000000000";  -- channel 12 phase increment
          s_axis_config_tdata(56 downto 32) <= "0000000000000000000000000";  -- channel 12 phase offset
      end case;
      if cfg_channel = 12 then
        s_axis_config_tlast <= '1';
      else
        s_axis_config_tlast <= '0';
      end if;
      wait for CLOCK_PERIOD;
    end loop;
    s_axis_config_tvalid <= '0';

    -- Run for long enough to produce 5 periods of outputs
    wait for CLOCK_PERIOD * 20007;

    -- Configure the core with a different configuration:
    --   set phase increment to half of its current value
    --   set phase offset to its current value plus PI radians
    -- Configure only channel 0 in this way; configure all other channels with zero configuration data
    s_axis_config_tvalid <= '1';
    s_axis_config_tdata <= (others => '0');  -- set unused TDATA bits to zero
    s_axis_config_tdata(24 downto 0) <= "0000000001101010011111101";  -- current phase increment / 2
    s_axis_config_tdata(56 downto 32) <= "0000110100011011011100011";  -- current phase offset + PI radians
    s_axis_config_tlast <= '0';
    wait for CLOCK_PERIOD;
    -- Configure other channels with zero configuration data
    for cfg_channel in 1 to 12 loop
      s_axis_config_tvalid <= '1';
      s_axis_config_tdata <= (others => '0');  -- set configuration data to zero
      if cfg_channel = 12 then
        s_axis_config_tlast <= '1';
      else
        s_axis_config_tlast <= '0';
      end if;
      wait for CLOCK_PERIOD;
    end loop;
    s_axis_config_tvalid <= '0';

    -- Run for long enough to produce 5 periods of outputs
    wait for CLOCK_PERIOD * 40014;

    -- End of test
    end_of_simulation <= true;           
    report "Not a real failure. Simulation finished successfully. Test completed successfully" severity failure;
    wait;

  end process stimuli;

  -----------------------------------------------------------------------
  -- Check outputs
  -----------------------------------------------------------------------

  check_outputs : process
    variable check_ok : boolean := true;
  begin

    -- Check outputs T_STROBE time after rising edge of clock
    wait until rising_edge(aclk);
    wait for T_STROBE;

    -- Do not check the output payload values, as this requires the behavioral model
    -- which would make this demonstration testbench unwieldy.
    -- Instead, check the protocol of the data and phase master channels:
    -- check that the payload is valid (not X) when TVALID is high

    if m_axis_data_tvalid = '1' then
      if is_x(m_axis_data_tdata) then
        report "ERROR: m_axis_data_tdata is invalid when m_axis_data_tvalid is high" severity error;
        check_ok := false;
      end if;

    end if;

    if m_axis_phase_tvalid = '1' then
      if is_x(m_axis_phase_tdata) then
        report "ERROR: m_axis_phase_tdata is invalid when m_axis_phase_tvalid is high" severity error;
        check_ok := false;
      end if;

    end if;

    assert check_ok
      report "ERROR: terminating test with failures." severity failure;

  end process check_outputs;

  -----------------------------------------------------------------------
  -- Assign TDATA fields to aliases, for easy simulator waveform viewing
  -----------------------------------------------------------------------

  -- Config slave channel alias signals
  s_axis_config_tdata_inc       <= s_axis_config_tdata(24 downto 0);
  s_axis_config_tdata_off       <= s_axis_config_tdata(56 downto 32);

  -- Data master channel alias signals: update these only when they are valid
  m_axis_data_tdata_sine        <= m_axis_data_tdata(7 downto 0) when m_axis_data_tvalid = '1';

  -- Data master channel alias signals for each TDM channel
  -- Note that these are one cycle later than the overall data master channel signals
  process (aclk)
  begin
    if rising_edge(aclk) then
      if m_axis_data_tvalid = '1' then
        if m_axis_data_channel = 12 then
          m_axis_data_channel <= 0;
        else
          m_axis_data_channel <= m_axis_data_channel + 1;
        end if;
        if m_axis_data_channel = 0 then
          m_axis_data_tdata_sine_c0     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 1 then
          m_axis_data_tdata_sine_c1     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 2 then
          m_axis_data_tdata_sine_c2     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 3 then
          m_axis_data_tdata_sine_c3     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 4 then
          m_axis_data_tdata_sine_c4     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 5 then
          m_axis_data_tdata_sine_c5     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 6 then
          m_axis_data_tdata_sine_c6     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 7 then
          m_axis_data_tdata_sine_c7     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 8 then
          m_axis_data_tdata_sine_c8     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 9 then
          m_axis_data_tdata_sine_c9     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 10 then
          m_axis_data_tdata_sine_c10     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 11 then
          m_axis_data_tdata_sine_c11     <= m_axis_data_tdata(7 downto 0);
        elsif m_axis_data_channel = 12 then
          m_axis_data_tdata_sine_c12     <= m_axis_data_tdata(7 downto 0);
        end if;
      end if;
    end if;
  end process;

  -- Phase master channel alias signals: update these only when they are valid
  m_axis_phase_tdata_phase      <= m_axis_phase_tdata(24 downto 0) when m_axis_phase_tvalid = '1';

  -- Phase master channel alias signals for each TDM channel
  -- Note that these are one cycle later than the overall phase master channel signals
  process (aclk)
  begin
    if rising_edge(aclk) then
      if m_axis_phase_tvalid = '1' then
        if m_axis_phase_channel = 12 then
          m_axis_phase_channel <= 0;
        else
          m_axis_phase_channel <= m_axis_phase_channel + 1;
        end if;
        if m_axis_phase_channel = 0 then
          m_axis_phase_tdata_phase_c0   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 1 then
          m_axis_phase_tdata_phase_c1   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 2 then
          m_axis_phase_tdata_phase_c2   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 3 then
          m_axis_phase_tdata_phase_c3   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 4 then
          m_axis_phase_tdata_phase_c4   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 5 then
          m_axis_phase_tdata_phase_c5   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 6 then
          m_axis_phase_tdata_phase_c6   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 7 then
          m_axis_phase_tdata_phase_c7   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 8 then
          m_axis_phase_tdata_phase_c8   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 9 then
          m_axis_phase_tdata_phase_c9   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 10 then
          m_axis_phase_tdata_phase_c10   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 11 then
          m_axis_phase_tdata_phase_c11   <= m_axis_phase_tdata(24 downto 0);
        elsif m_axis_phase_channel = 12 then
          m_axis_phase_tdata_phase_c12   <= m_axis_phase_tdata(24 downto 0);
        end if;
      end if;
    end if;
  end process;

end tb;

