# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {Place 30-99}  -string {{ERROR: [Place 30-99] Placer failed with error: 'IO Clock Placer failed'
Please review all ERROR, CRITICAL WARNING, and WARNING messages during placement to understand the cause for failure.}}  -suppress 
set_msg_config  -ruleid {2}  -id {Place 30-574}  -string {{ERROR: [Place 30-574] Poor placement for routing between an IO pin and BUFG. If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
	< set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF] >

	clk_IBUF_inst (IBUF.O) is locked to IOB_X1Y96
	 and clk_IBUF_BUFG_inst (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y0
Resolution: Poor placement of an IO pin and a BUFG has resulted in the router using a non-dedicated path between the two.  There are several things that could trigger this DRC, each of which can cause unpredictable clock insertion delays that result in poor timing.  This DRC could be caused by any of the following: (a) a clock port was placed on a pin that is not a CCIO-pin (b)the BUFG has not been placed in the same half of the device or SLR as the CCIO-pin (c) a single ended clock has been placed on the N-Side of a differential pair CCIO-pin.}}  -suppress 
set_msg_config  -ruleid {3}  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Placer could not place all instances}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/alexa/Documents/GitHub/QAM/QAM.cache/wt [current_project]
set_property parent.project_path D:/Users/alexa/Documents/GitHub/QAM/QAM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Users/alexa/Documents/GitHub/QAM/QAM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test.xci
set_property used_in_implementation false [get_files -all d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1 -new_name dds_compiler_test -ip [get_ips dds_compiler_test]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top dds_compiler_test -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix dds_compiler_test_ dds_compiler_test.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dds_compiler_test_stub.v
 lappend ipCachedFiles dds_compiler_test_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dds_compiler_test_stub.vhdl
 lappend ipCachedFiles dds_compiler_test_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dds_compiler_test_sim_netlist.v
 lappend ipCachedFiles dds_compiler_test_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dds_compiler_test_sim_netlist.vhdl
 lappend ipCachedFiles dds_compiler_test_sim_netlist.vhdl

 config_ip_cache -add -dcp dds_compiler_test.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips dds_compiler_test]
}

rename_ref -prefix_all dds_compiler_test_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dds_compiler_test.dcp
create_report "dds_compiler_test_synth_1_synth_report_utilization_0" "report_utilization -file dds_compiler_test_utilization_synth.rpt -pb dds_compiler_test_utilization_synth.pb"

if { [catch {
  file copy -force D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1/dds_compiler_test.dcp d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1/dds_compiler_test.dcp d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1/dds_compiler_test_stub.v d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1/dds_compiler_test_stub.vhdl d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1/dds_compiler_test_sim_netlist.v d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Users/alexa/Documents/GitHub/QAM/QAM.runs/dds_compiler_test_synth_1/dds_compiler_test_sim_netlist.vhdl d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/Users/alexa/Documents/GitHub/QAM/QAM.ip_user_files/ip/dds_compiler_test]} {
  catch { 
    file copy -force d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_stub.v D:/Users/alexa/Documents/GitHub/QAM/QAM.ip_user_files/ip/dds_compiler_test
  }
}

if {[file isdir D:/Users/alexa/Documents/GitHub/QAM/QAM.ip_user_files/ip/dds_compiler_test]} {
  catch { 
    file copy -force d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_stub.vhdl D:/Users/alexa/Documents/GitHub/QAM/QAM.ip_user_files/ip/dds_compiler_test
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
