# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test.xci
# IP: The module: 'dds_compiler_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_test'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test.xci
# IP: The module: 'dds_compiler_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/alexa/Documents/GitHub/QAM/QAM.srcs/sources_1/ip/dds_compiler_test/dds_compiler_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
